apiVersion: v1
kind: Service
metadata:
  name: talkdesk-svc
spec:
  type: ClusterIP
  selector:
    app: talkdesk
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talkdesk-deployment
  labels:
    app: talkdesk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talkdesk
  template:
    metadata:
      labels:
        app: talkdesk
    spec:
      containers:
      - name: talkdesk
        image: bharathshetty4/supermario
        ports:
        - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talkdesk-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  defaultBackend:
    service:
      name: talkdesk-svc
      port:
        number: 8080