---
  - name: Deploying via Ansible
    hosts: localhost
    vars_prompt:
      - name: "aws_access_key"
        prompt: "Please write your AWS_ACCESS_KEY"
      - name: "aws_secret_key"
        prompt: "Please write your AWS_SECRET_KEY"
    
    tasks:
    - name: Run Terraform scripts
      shell: |
         cd ../terraform/
         echo "Set AWS credentials"
         sed -i '/access_key = ""/c\  access_key = "{{ aws_access_key }}"' provider.tf
         sed -i '/secret_key = ""/c\  secret_key = "{{ aws_secret_key }}"' provider.tf
         echo "Starting terraform initialization"
         terraform init
         terraform apply -var 'env=dr' -auto-approve
         terraform output kubectl_config > output
         sed '$d' < output | sed "1d" > config
         cp config ../ansible/
      register: terraform
      async: 3600
      poll: 10
    - debug: msg="{{terraform.stdout_lines}}"

    - name: Deploy Nginx ingress
      shell: |
         echo "Deploying Nginx Ingress"
         kubectl --kubeconfig=config apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/aws/deploy.yaml
      register: ingress
      async: 3600
      poll: 10
    - debug: msg="{{ingress.stdout_lines}}"

    - name: Run deployment manifests
      shell: |
        echo "Deploying on Kubernetes"
        kubectl --kubeconfig=config apply -f deployment.yaml
        kubectl --kubeconfig=config rollout status deployment talkdesk-deployment
        
        echo "Waiting for ingress/dns/public access become ready..."
        sleep 5m
       
        echo "Here is the link you can open to see the final result:"
        kubectl --kubeconfig=config get ingress talkdesk-ingress | awk '{ print $4}' | tail -n +2
      register: nodelist
    - debug: msg="{{nodelist.stdout_lines}}"